### ISSUE TITLE
Urlencode when filtering?

### ISSUE THREAD

**Issue by edsu** [J535D165/pyalex#41]
Thanks for pyalex, it provides a really intuitive interface to the OpenAlex API!

One small issue I ran into is where a DOI with an ampersand in it (these exist I guess) was causing an API error:

```python
>>> pyalex.Works().filter(doi='10.1207/s15327809jls0703&4_2').get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/edsu/Projects/sul-dlss/rialto-airflow/.venv/lib/python3.12/site-packages/pyalex/api.py", line 293, in get
    return self._get_from_url(self.url, return_meta=return_meta)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edsu/Projects/sul-dlss/rialto-airflow/.venv/lib/python3.12/site-packages/pyalex/api.py", line 265, in _get_from_url
    raise QueryError(res.json()["message"])
pyalex.api.QueryError: 4_2 is not a valid parameter. Valid parameters are: apc_sum, cited_by_count_sum, cursor, filter, format, group_by, group-by, group_bys, group-bys, mailto, page, per_page, per-page, q, sample, seed, search, select, sort.
```

However URL encoding the ampersand allows it to work:

```python
>>> pyalex.Works().filter(doi='10.1207/s15327809jls0703%264_2').get()
[{'id': 'https://openalex.org/W4238483711', 'doi': 'https://doi.org/10.1207/s15327809jls0703&4_2', 'title': 'Doing With Understanding: Lessons From Research on Problem and Project-Based Learning', 'display_name': 'Doing With Understanding: Lessons From Research on Problem and Project-Based Learning', 'publication_year': 1998, 'publication_date': '1998-07-01', 'ids': {'openalex': 'https://openalex.org/W4238483711', 'doi': 'https://doi.org/10.1207/s15327809jls0703&4_2'}, 'language': 'en', 'primary_location': {'is_oa': False, 'landing_page_url': 'https://doi.org/10.1207/s15327809jls0703&4_2', 'pdf_url': None, 'source': {'id': 'https://openalex.org/S42640028', 'display_name': '\x98The \x9cJournal of the learning sciences/\x98The \x9cjournal of the learning sciences', 'issn_l': '1050-8406', 'issn': ['1050-8406', '1532-7809'], 'is_oa': False, 'is_in_doaj': False, 'host_organization': 'https://openalex.org/P4310319847', 'host_organization_name': 'Routledge', 'host_organization_lineage': ['https://openalex.org/P4310319847'], 'host_organization_lineage_names': ['Routledge'], 'type': 'journal'}, 'license': None, 'license_id': None, 'version': None, 'is_accepted': False, 'is_published': False}, 'type': 'article', 'type_crossref': 'journal-article', 'indexed_in': ['crossref'], 'open_access': {'is_oa': False, 'oa_status': 'closed', 'oa_url': None, 'any_repository_has_fulltext': False}, 'authorships': [{'author_position': 'first', 'author': {'id': 'https://openalex.org/A5083458281', 'display_name': 'Brigid Barron', 'orcid': 'https://orcid.org/0000-0003-4693-9374'}, 'institutions': [], 'countries': [], 'is_corresponding': False, 'raw_author_name': 'Brigid Barron', 'raw_affiliation_strings': [], 'affiliations': []}, {'author_position': 'middle', 'author': {'id': 'https://openalex.org/A5051614604', 'display_name': 'D. A. Schwartz', 'orcid': 'https://orcid.org/0000-0001-8252-4753'}, 'institutions': [], 'countries': [], 'is_corresponding': False, 'raw_author_name': 'Daniel Schwartz', 'raw_affiliation_strings': [], 'affiliations': []}, {'author_position': 'middle', 'author': {'id': 'https://openalex.org/A5040516303', 'display_name': 'Nancy Vye', 'orcid': None}, 'institutions': [], 'countries': [], 'is_corresponding': False, 'raw_author_name': 'Nancy Vye', 'raw_affiliation_strings': [], 'affiliations': []}, {'author_position': 'middle', 'author': {'id': 'https://openalex.org/A5065201976', 'display_name': 'Allison Moore', 'orcid': None}, 'institutions': [], 'countries': [], 'is_corresponding': False, 'raw_author_name': 'Allison Moore', 'raw_affiliation_strings': [], 'affiliations': []}, {'author_position': 'middle', 'author': {'id': 'https://openalex.org/A5036279083', 'display_name': 'Anthony Petrosino', 'orcid': 'https://orcid.org/0000-0002-2048-8993'}, 'institutions': [], 'countries': [], 'is_corresponding': False, 'raw_author_name': 'Anthony Petrosino', 'raw_affiliation_strings': [], 'affiliations': []}, {'author_position': 'middle', 'author': {'id': 'https://openalex.org/A5001803030', 'display_name': 'Linda Zech', 'orcid': None}, 'institutions': [], 'countries': [], 'is_corresponding': False, 'raw_author_name': 'Linda Zech', 'raw_affiliation_strings': [], 'affiliations': []}, {'author_position': 'last', 'author': {'id': 'https://openalex.org/A5015154801', 'display_name': 'John D. Bransford', 'orcid': None}, 'institutions': [], 'countries': [], 'is_corresponding': False, 'raw_author_name': 'John Bransford', 'raw_affiliation_strings': [], 'affiliations': []}], 'countries_distinct_count': 0, 'institutions_distinct_count': 0, 'corresponding_author_ids': [], 'corresponding_institution_ids': [], 'apc_list': None, 'apc_paid': None, 'fwci': 5.274, 'has_fulltext': False, 'cited_by_count': 153, 'cited_by_percentile_year': {'min': 97, 'max': 98}, 'biblio': {'volume': '7', 'issue': '3', 'first_page': '271', 'last_page': '311'}, 'is_retracted': False, 'is_paratext': False, 'primary_topic': {'id': 'https://openalex.org/T11299', 'display_name': 'Impact and Implementation of Problem-Based Learning in Education', 'score': 0.9265, 'subfield': {'id': 'https://openalex.org/subfields/3304', 'display_name': 'Education'}, 'field': {'id': 'https://openalex.org/fields/33', 'display_name': 'Social Sciences'}, 'domain': {'id': 'https://openalex.org/domains/2', 'display_name': 'Social Sciences'}}, 'topics': [{'id': 'https://openalex.org/T11299', 'display_name': 'Impact and Implementation of Problem-Based Learning in Education', 'score': 0.9265, 'subfield': {'id': 'https://openalex.org/subfields/3304', 'display_name': 'Education'}, 'field': {'id': 'https://openalex.org/fields/33', 'display_name': 'Social Sciences'}, 'domain': {'id': 'https://openalex.org/domains/2', 'display_name': 'Social Sciences'}}], 'keywords': [{'id': 'https://openalex.org/keywords/problem-based-learning', 'display_name': 'Problem-Based Learning', 'score': 0.716976}, {'id': 'https://openalex.org/keywords/project-based-learning', 'display_name': 'Project-Based Learning', 'score': 0.714351}, {'id': 'https://openalex.org/keywords/team-based-learning', 'display_name': 'Team-Based Learning', 'score': 0.619677}, {'id': 'https://openalex.org/keywords/critical-thinking', 'display_name': 'Critical Thinking', 'score': 0.55983}, {'id': 'https://openalex.org/keywords/active-learning', 'display_name': 'Active Learning', 'score': 0.551498}], 'concepts': [{'id': 'https://openalex.org/C36727532', 'wikidata': 'https://www.wikidata.org/wiki/Q861399', 'display_name': 'Educational research', 'level': 2, 'score': 0.4170767}, {'id': 'https://openalex.org/C44877443', 'wikidata': 'https://www.wikidata.org/wiki/Q2485457', 'display_name': 'Science education', 'level': 2, 'score': 0.41538996}, {'id': 'https://openalex.org/C145420912', 'wikidata': 'https://www.wikidata.org/wiki/Q853077', 'display_name': 'Mathematics education', 'level': 1, 'score': 0.40167567}, {'id': 'https://openalex.org/C41008148', 'wikidata': 'https://www.wikidata.org/wiki/Q21198', 'display_name': 'Computer science', 'level': 0, 'score': 0.38806325}, {'id': 'https://openalex.org/C539667460', 'wikidata': 'https://www.wikidata.org/wiki/Q2414942', 'display_name': 'Management science', 'level': 1, 'score': 0.36439627}, {'id': 'https://openalex.org/C15744967', 'wikidata': 'https://www.wikidata.org/wiki/Q9418', 'display_name': 'Psychology', 'level': 0, 'score': 0.2330338}, {'id': 'https://openalex.org/C127413603', 'wikidata': 'https://www.wikidata.org/wiki/Q11023', 'display_name': 'Engineering', 'level': 0, 'score': 0.21014354}], 'mesh': [], 'locations_count': 1, 'locations': [{'is_oa': False, 'landing_page_url': 'https://doi.org/10.1207/s15327809jls0703&4_2', 'pdf_url': None, 'source': {'id': 'https://openalex.org/S42640028', 'display_name': '\x98The \x9cJournal of the learning sciences/\x98The \x9cjournal of the learning sciences', 'issn_l': '1050-8406', 'issn': ['1050-8406', '1532-7809'], 'is_oa': False, 'is_in_doaj': False, 'host_organization': 'https://openalex.org/P4310319847', 'host_organization_name': 'Routledge', 'host_organization_lineage': ['https://openalex.org/P4310319847'], 'host_organization_lineage_names': ['Routledge'], 'type': 'journal'}, 'license': None, 'license_id': None, 'version': None, 'is_accepted': False, 'is_published': False}], 'best_oa_location': None, 'sustainable_development_goals': [], 'grants': [], 'datasets': [], 'versions': [], 'referenced_works_count': 0, 'referenced_works': [], 'related_works': ['https://openalex.org/W4235964211', 'https://openalex.org/W2894723147', 'https://openalex.org/W283532838', 'https://openalex.org/W2797357684', 'https://openalex.org/W2604819331', 'https://openalex.org/W2046904434', 'https://openalex.org/W2043561493', 'https://openalex.org/W2022745980', 'https://openalex.org/W2010171853', 'https://openalex.org/W1542902583'], 'ngrams_url': 'https://api.openalex.org/works/W4238483711/ngrams', 'abstract_inverted_index': None, 'cited_by_api_url': 'https://api.openalex.org/works?filter=cites:W4238483711', 'counts_by_year': [{'year': 2024, 'cited_by_count': 2}, {'year': 2023, 'cited_by_count': 9}, {'year': 2022, 'cited_by_count': 2}, {'year': 2021, 'cited_by_count': 8}, {'year': 2020, 'cited_by_count': 8}, {'year': 2019, 'cited_by_count': 15}, {'year': 2018, 'cited_by_count': 9}, {'year': 2017, 'cited_by_count': 6}, {'year': 2016, 'cited_by_count': 1}, {'year': 2015, 'cited_by_count': 5}, {'year': 2014, 'cited_by_count': 10}, {'year': 2013, 'cited_by_count': 6}, {'year': 2012, 'cited_by_count': 15}], 'updated_date': '2024-06-22T05:53:11.188295', 'created_date': '2022-05-12'}]
```

I was wondering if filter parameter values should be URL encoded before using them to construct a URL to GET?

Perhaps this is an issue in places other than filter?

**Comment by J535D165** [comment]
Thanks for the compliment and the PR. Merged.

Recently, I stumbled on DOIs with special characters in another project (https://github.com/J535D165/datahugger) as well. I didn't know that was allowed. I will apply your fix there as well. Thanks.
